<script>
	import Prism from 'prismjs';
	import 'prismjs/themes/prism-tomorrow.css';
	import 'prismjs/components/prism-python';
	import 'prismjs/components/prism-java';

	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';

	/**
	 * The user's input code
	 * @type {string}
	 */
	let code = '';

	/**
	 * The language selected for translation
	 * @type {string}
	 */
	let language = 'javascript';

	/**
	 * Text generated by GPT-3 for JavaScript
	 * @type {string}
	 */
	let gptJS = ` `;

	/**
	 * Text generated by GPT-3 for Python
	 * @type {string}
	 */
	let gptPython = ` `;

	/**
	 * Text generated by GPT-3 for C++
	 * @type {string}
	 */
	let gptCPP = ` `;

	/**
	 * Text generated by GPT-3 for Java
	 * @type {string}
	 */
	let gptJava = ` `;

	/**
	 * The Firebase app
	 * @type {Object}
	 */
	let app;

	/**
	 * The Firebase authentication object
	 * @type {Object}
	 */
	let auth;

	/**
	 * The Firebase analytics object
	 * @type {Object}
	 */
	let analytics;

	/**
	 * The stored usage timestamp
	 * @type {Object}
	 */
	let storedUsage;

	/**
	 * The timestamp of the last usage
	 * @type {number}
	 */
	var lastUsage = 0;

	/**
	 * The final translated output text
	 * @type {string}
	 */
	let outputFinalText;

	/**
	 * The status of the translation process
	 * @type {string}
	 */
	let status = '';

	/**
	 * Calls both `postModData` and `postData`
	 */
	async function submit() {
		status = '⏱️loading...';
		const now = Date.now();
		//5 seconds
		if (Date.now() - lastUsage >= 5 * 1000) {
			outputFinalText = 'loading..';
			let allowedInput = await postModData(code);
			if (allowedInput.toLowerCase().includes('good')) {
				outputFinalText = await postData(code, language);
				lastUsage = Date.now();
				storedUsage.subscribe(() => {
					localStorage.setItem('storedUsage', JSON.stringify(Date.now()));
				});
			} else {
				outputFinalText = 'This input is not allowed 😡';
				status = 'This input is not allowed 😡';
			}
		} else {
			outputFinalText = 'Please wait a moment...';
			status = 'Please wait a moment...';
		}
	}

	/**
	 * Posts the user's input code to the translation API for all supported languages
	 * @param {string} inputText - The user's input code
	 * @param {string} language - The selected input language
	 * @returns {Promise<string[]>} - An array of the translated output texts for each language
	 */
	async function postData(inputText, language) {
		let languagesToTranslate = ['javascript', 'python', 'c++', 'java'];
		let outputText = ['JS', 'Python', 'C++', 'Java'];
		try {
			for (let tempLanguage in languagesToTranslate) {
				// console.log(
				// 	'🚀 ~ file: +page.svelte:52 ~ postData ~ tempLanguage:',
				// 	languagesToTranslate[tempLanguage]
				// );

				status = `loading ${languagesToTranslate[tempLanguage]}...`;

				const response = await fetch('/api', {
					method: 'POST',
					body: JSON.stringify({
						inputText: inputText,
						fromLanguage: language,
						toLanguage: languagesToTranslate[tempLanguage]
					}),
					headers: {
						'content-type': 'application/json'
					}
				});
				if (languagesToTranslate[tempLanguage] == 'javascript') {
					outputText[0] = await response.json();

					gptJS = outputText[0];
					let jsBlock = document.querySelector('.language-javascript');
					jsBlock.innerHTML = `<code class="language-javascript">${gptJS}</code>`;
				} else if (languagesToTranslate[tempLanguage] == 'python') {
					outputText[1] = await response.json();
					gptPython = outputText[1];
					let pythonBlock = document.querySelector('.language-python');
					pythonBlock.innerHTML = `<code class="language-python">${gptPython}</code>`;
				} else if (languagesToTranslate[tempLanguage] == 'c++') {
					outputText[2] = await response.json();
					gptCPP = outputText[2];
					let cppBlock = document.querySelector('.language-clike');
					cppBlock.innerHTML = `<code class="language-clike">${gptCPP}</code>`;
				} else if (languagesToTranslate[tempLanguage] == 'java') {
					outputText[3] = await response.json();
					gptJava = outputText[3];
					let javaBlock = document.querySelector('.language-java');
					javaBlock.innerHTML = `<code class="language-java">${gptJava}</code>`;
				}
				setTimeout(() => {
					Prism.highlightAll();
				}, 100);
				// console.log('🚀 ~ file: +page.svelte:17 ~ postData ~ outputText:', outputText);
			}
		} catch {
			outputText = 'An error occurred👽';
		}
		return outputText;
	}

	/**
	 * Posts the user's input code to the moderation API
	 * @param {string} inputText - The user's input code
	 * @returns {Promise<string>} - The moderation API's response text
	 */
	async function postModData(inputText) {
		let outputText = '';
		try {
			const response = await fetch('/mod', {
				method: 'POST',
				body: JSON.stringify({ inputText: inputText }),
				headers: {
					'content-type': 'application/json'
				}
			});
			outputText = await response.json();
		} catch {
			outputText = 'An error occurred👽';
		}
		return outputText;
	}

	import { initializeApp } from 'firebase/app';
	import { getAnalytics } from 'firebase/analytics';
	import { getAuth, signInAnonymously } from 'firebase/auth';

	const firebaseConfig = {
		apiKey: 'AIzaSyDulIaauIfYaPyQNzyvBwXH70BdYLx_HeI',
		authDomain: 'polyglot-code.firebaseapp.com',
		projectId: 'polyglot-code',
		storageBucket: 'polyglot-code.appspot.com',
		messagingSenderId: '98506944926',
		appId: '1:98506944926:web:525a3e857ebd686604268f',
		measurementId: 'G-RNKPQQRDZM'
	};

	/**
	 * The user's id
	 * @type {string}
	 */
	let userId;

	/**
	 * Anonymously logs the user in using Firebase
	 */
	function logIn() {
		signInAnonymously(auth)
			.then(() => {
				userId = auth.currentUser.uid;
			})
			.catch((error) => {
				const errorCode = error.code;
				const errorMessage = error.message;
			});
	}

	onMount(async () => {
		storedUsage = writable(localStorage.getItem('storedUsage'));
		storedUsage.subscribe((value) => {
			if (value != null) {
				lastUsage = JSON.parse(value);
			} else {
				lastUsage = Date.now();
			}
		});
		app = initializeApp(firebaseConfig);
		analytics = getAnalytics(app);
		auth = getAuth();
		logIn();
	});
</script>

<div class="flex max-md:flex-col h-screen">
	<div class="w-1/2 max-md:w-full px-4 py-8">
		<p class="text-left pb-8 max-md:text-center text-blue-400">
			Usage: Choose input language ➡️ Write code ➡️ Click Translate 😍
		</p>
		<div class="mb-4">
			<select
				class="w-full h-10 px-3 py-2 border rounded-lg"
				aria-label="Select a programming language"
				title="Select a programming language"
				bind:value={language}
			>
				<option value="javascript">JavaScript</option>
				<option value="python">Python</option>
				<option value="c++">C++</option>
				<option value="java">Java</option>
			</select>
		</div>
		<div class="mb-4">
			<textarea
				class="w-full h-64 px-3 py-2 border rounded-lg"
				placeholder="enter your {language} code here👨‍💻"
				bind:value={code}
			/>
		</div>

		<div class="flex">
			<button
				aria-label="Translate code to the other programming languages"
				title="Translate code to the other programming languages"
				on:click={async () => {
					await submit();
					status = 'loading color🎨...';
					// console.log(gptJS, gptPython, gptJava, gptCPP);

					// let jsBlock = document.querySelector('.language-javascript');
					// jsBlock.innerHTML = `<code class="language-javascript">${gptJS}</code>`;
					// let pythonBlock = document.querySelector('.language-python');
					// pythonBlock.innerHTML = `<code class="language-python">${gptPython}</code>`;
					// let javaBlock = document.querySelector('.language-java');
					// javaBlock.innerHTML = `<code class="language-java">${gptJava}</code>`;
					// let cppBlock = document.querySelector('.language-clike');
					// cppBlock.innerHTML = `<code class="language-clike">${gptCPP}</code>`;

					setTimeout(() => {
						Prism.highlightAll();
					}, 100);
					status = '';
				}}
				class="px-4 py-2 text-white bg-blue-500 rounded-lg hover:bg-blue-700 max-md:m-auto"
				>Translate😍</button
			>
			<p class="p-3 flex-1 text-white max-md:m-auto">{status}</p>
		</div>
	</div>

	<div class="w-1/2 p-8">
		<p class="text-green-300">JavaScript🌐</p>
		<pre class="rounded-md max-md:w-80"><code class="language-javascript">{gptJS}</code></pre>
		<p class="text-green-300">Python🐍</p>
		<pre class="rounded-md max-md:w-80"><code class="language-python">{gptPython}</code></pre>
		<p class="text-green-300">C++🐢</p>
		<pre class="rounded-md max-md:w-80"><code class="language-clike">{gptCPP}</code></pre>
		<p class="text-green-300">Java☕</p>
		<pre class="rounded-md max-md:w-80"><code class="language-java">{gptJava}</code></pre>
	</div>
</div>
